# Generated by Django 6.0.6 on 2026-07-05 15:22

import classroom.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_code', models.CharField(default=classroom.models.generate_test_code, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('passage', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('answer_key', models.TextField()),
                ('blooms_level', models.CharField(choices=[('REMEMBER', 'Remembering'), ('UNDERSTAND', 'Understanding'), ('APPLY', 'Applying'), ('ANALYZE', 'Analyzing'), ('EVALUATE', 'Evaluating'), ('CREATE', 'Creating')], editable=False, max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
