# Generated by Django 6.0.6 on 2026-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_grounded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_relevant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_similar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
