# Generated by Django 6.0.7 on 2026-07-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_studentanswer_is_grounded_studentanswer_is_relevant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_similar',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='bert_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='gate_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.FloatField()),
                ('phil_iri_level', models.CharField(choices=[('INDEPENDENT', 'Independent'), ('INSTRUCTIONAL', 'Instructional'), ('FRUSTRATION', 'Frustration')], max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='classroom.test')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
    ]
