# Generated by Django 6.0.7 on 2026-07-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
