# Generated by Django 6.0.7 on 2026-08-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_studentanswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_grounded',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_relevant',
        ),
    ]
