# Generated by Django 6.0.7 on 2026-08-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_studentanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='gate_score',
        ),
    ]
