# Generated by Django 6.0.7 on 2026-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_remove_studentanswer_gate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passage_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='passage_timer_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='separate_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='shown_in_test',
            field=models.BooleanField(default=True),
        ),
    ]
