# Generated by Django 6.0.7 on 2026-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_classroom_test_classroom_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
